Update Developer Guide
AY2223S2-CS2103T-W14-2/tp pull request #180
Opened 2023-03-23 14:21 UTC by zichen-3974

Changes:
- Update UI component documentation.
- Update class diagram for UI.

2023-03-23 17:10 UTC, seanfirefox requested changes
LGTM! Just a minor change needed below.

2023-03-24 00:04 UTC, russelltankaimin requested changes
LGTM, just requesting a quick change.

2023-03-24 00:04 UTC, russelltankaimin commented on docs/DeveloperGuide.md
>  {to be filled by Zichen}
Do you want to remove this as well?

2023-03-24 00:45 UTC, seanfirefox approved these changes
LGTM!

2023-03-24 00:48 UTC, russelltankaimin commented
LGTM

2023-03-24 00:48 UTC, russelltankaimin approved these changes

2023-03-24 00:49 UTC, merged